dist: xenial
services:
  - xvfb

language: python
python:
- 2.7
- 3.5
- 3.6
install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install pytest-cov
- pip install coveralls
before_script:
- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"
- sleep 3
script:
- py.test --mpl
after_success:
- coveralls
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: Lx85Q76ySzPqV8+fy6uW8awxbVTkYQrRyiwe69RtxZK70KgZqLQS8oxnZvphlybhOOQ5JsnuXqPBbp6rFrOi9tY6iaHfWkHW5n9eHW87UQhVAbl4RjeJoy521x3ta2UsV65uaZBfY8wdjJJ+k/PaxLosIwU1IXSKe5HDxIi9oe4vbpwTOxFN0N9vR3zV/i4DRSeyufTA130WhLNcS1rO69mK2zkem/rwGV1awHdNALmTXT9/3SrdhXWtvSHv0rfPo1d4L8GaFz3uRBGkaJtaBFKskLSJT9DcAV5JhdOX6Q8mZNXEvhHHeTZDSaWOnXMGInCENb/TJFBSuweR1XYbiLji24n6qdcj4VzpU1SyB4jDcO5vUoIYWAu6SxZR12i5ii2pDyuExZvBgP0W5REAobmvr1LEuOm9PL8/NFw0cMMxUyeaQzb3bv4cNG3dMZ9aWA0PCw8uCT+zah6fYIEafRkbkd8K4AjMrQjYUEc2UGPyibdXtqP4VEz4qJWPhznJSxCoYeSTHfLX5a87/XR7+tpqVItolNOCTyqv9M+HQuha8+PSjKz0lgtRuNq/+MkE5V1sb23XSY5dQj/RGdOIcqNkBqz8+PHyJd2jgro0wtSELV6OStOBsLaAOdFOLA3Ipi7QZxnc3mP+T8EqQ8halksqQQDqch5bXOUEulLuPGU=
  on:
    tags: true
